services:
    squeezelite1:
        container_name: squeezelite1
        build:
            context: ./squeezelite
        image: squeezelite
        network_mode: host
        restart: unless-stopped
        devices:
            - "/dev/snd"
            - "/dev/gpiomem"
        ipc: host
        volumes:
            - type: bind
              source: /etc/asound.conf
              target: /etc/asound.conf
              read_only: true
            - type: bind
              source: /home/pi/squeezenames/squeeze1.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch1
            - MAC_ADDRESS=02:00:00:00:00:01
            - GPIO="15;7;15:18:22:31:32:36:35:40;11"
    squeezelite2:
        container_name: squeezelite2
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze2.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch2
            - MAC_ADDRESS=02:00:00:00:00:02
            - GPIO="18;7;15:18:22:31:32:36:35:40"
    squeezelite3:
        container_name: squeezelite3
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze3.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch3
            - MAC_ADDRESS=02:00:00:00:00:03
            - GPIO="22;7;15:18:22:31:32:36:35:40"
    squeezelite4:
        container_name: squeezelite4
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze4.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch4
            - MAC_ADDRESS=02:00:00:00:00:04
            - GPIO="31;7;15:18:22:31:32:36:35:40"
    squeezelite5:
        container_name: squeezelite5
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze5.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch5
            - MAC_ADDRESS=02:00:00:00:00:05
            - GPIO="32;7;15:18:22:31:32:36:35:40"
    squeezelite6:
        container_name: squeezelite6
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze6.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch6
            - MAC_ADDRESS=02:00:00:00:00:06
            - GPIO="36;7;15:18:22:31:32:36:35:40"
   squeezelite7:
        container_name: squeezelite7
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze7.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch7
            - MAC_ADDRESS=02:00:00:00:00:07
            - GPIO="35;7;15:18:22:31:32:36:35:40"
    squeezelite8:
        container_name: squeezelite8
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze8.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=ch8
            - MAC_ADDRESS=02:00:00:00:00:08
            - GPIO="40;7;15:18:22:31:32:36:35:40"
    hermes:
        container_name: hermes1
        build:
            context: ./hermesAudioPlayer
        image: hermes
        network_mode: host
        restart: unless-stopped
        devices:
            - "/dev/snd"
            - "/dev/gpiomem"
        ipc: host
        volumes:
            - type: bind
              source: /etc/asound.conf
              target: /etc/asound.conf
              read_only: true
        environment:
            - MQTT=localhost:1883
            - LMS=tower:9000
            - SITE_ID=hermes-one
            - OUTPUT_DEVICE=ch1
            - MAC_ADDRESS=02:00:00:00:00:01
            - GPIO="15;7;15:18:22:31:32:36:35:40"