services:
    squeezelite1:
        container_name: squeezelite1
        profiles: ["${CH1_SQUEEZELITE}"]
        build:
            context: ./squeezelite
        image: squeezelite
        network_mode: host
        restart: unless-stopped
        devices:
            - "/dev/snd"
            - "/dev/gpiomem"
        ipc: host
        volumes:
            - /etc/opt/eq:/etc/opt/eq
            - type: bind
              source: /etc/asound.conf
              target: /etc/asound.conf
              read_only: true
            - type: bind
              source: /home/pi/squeezenames/squeeze1.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH1}
            - MAC_ADDRESS=02:00:00:00:00:01
            - GPIO=${GPIO_CH1_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH1_SPS}
    squeezelite2:
        container_name: squeezelite2
        profiles: ["${CH2_SQUEEZELITE}"]
        extends:
            service: squeezelite1
        volumes:
            - /etc/opt/eq:/etc/opt/eq
            - type: bind
              source: /home/pi/squeezenames/squeeze2.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH2}
            - MAC_ADDRESS=02:00:00:00:00:02
            - GPIO=${GPIO_CH2_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH2_SPS}
    squeezelite3:
        container_name: squeezelite3
        profiles: ["${CH3_SQUEEZELITE}"]
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze3.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH3}
            - MAC_ADDRESS=02:00:00:00:00:03
            - GPIO=${GPIO_CH3_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH3_SPS}
    squeezelite4:
        container_name: squeezelite4
        profiles: ["${CH4_SQUEEZELITE}"]
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze4.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH4}
            - MAC_ADDRESS=02:00:00:00:00:04
            - GPIO=${GPIO_CH4_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH4_SPS}
    squeezelite5:
        container_name: squeezelite5
        profiles: ["${CH5_SQUEEZELITE}"]
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze5.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH5}
            - MAC_ADDRESS=02:00:00:00:00:05
            - GPIO=${GPIO_CH5_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH5_SPS}
    squeezelite6:
        container_name: squeezelite6
        profiles: ["${CH6_SQUEEZELITE}"]
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze6.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH6}
            - MAC_ADDRESS=02:00:00:00:00:06
            - GPIO=${GPIO_CH6_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH6_SPS}
    squeezelite7:
        container_name: squeezelite7
        profiles: ["${CH7_SQUEEZELITE}"]
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze7.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH7}
            - MAC_ADDRESS=02:00:00:00:00:07
            - GPIO=${GPIO_CH7_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH7_SPS}
    squeezelite8:
        container_name: squeezelite8
        profiles: ["${CH8_SQUEEZELITE}"]
        extends:
            service: squeezelite1
        volumes:
            - type: bind
              source: /home/pi/squeezenames/squeeze8.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH8}
            - MAC_ADDRESS=02:00:00:00:00:08
            - GPIO=${GPIO_CH8_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH8_SPS}
    hermes1:
        container_name: hermes1
        profiles: ["${CH1_HERMES}"]
        build:
            context: ./hermesAudioPlayer
        image: hermes
        network_mode: host
        restart: unless-stopped
        devices:
            - "/dev/snd"
            - "/dev/gpiomem"
        ipc: host
        volumes:
            - /etc/opt/eq:/etc/opt/eq
            - type: bind
              source: /etc/asound.conf
              target: /etc/asound.conf
              read_only: true
            - type: bind
              source: /home/pi/squeezenames/squeeze1.name
              target: /config/squeeze.name
        environment:
            - OUTPUT_DEVICE=${OUTPUT_CH1}
            - MAC_ADDRESS=02:00:00:00:00:01
            - GPIO=${GPIO_CH1_MUTE};${GPIO_RELAY};${GPIO_RELAY_CHANNELS};${GPIO_CH1_SPS}
